import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createDesktopServer} from '../server/desktop-http.mjs';
const token='local-test-token-0123456789012345';
async function setup(t){const forwarded=[],starts=[];const server=createDesktopServer({token,publicDir:new URL('../public',import.meta.url),request:async(p,b)=>{forwarded.push({p,b});return {tasks:[],capabilities:{cloud:true,cloudCodex:true}};},bridge:{status:()=>({busy:false}),startTask:async(id,b)=>{starts.push({id,b});return {id,status:'running'};}}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));return {base:'http://127.0.0.1:'+server.address().port,forwarded,starts};}
test('desktop source endpoint requires local auth and never forwards source bytes',async t=>{const f=await setup(t);const body={provider:'codex',expectedVersion:1,materials:[{name:'a.txt',text:'PRIVATE_SOURCE'}]};assert.equal((await fetch(f.base+'/api/tasks/t/run',{method:'POST',body:JSON.stringify(body)})).status,401);const r=await fetch(f.base+'/api/tasks/t/run',{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(body)});assert.equal(r.status,202);assert.equal(f.starts[0].b.materials[0].text,'PRIVATE_SOURCE');assert.equal(f.forwarded.length,0);});
test('desktop page exposes cloud-backed source capability but no credentials',async t=>{const f=await setup(t);const r=await fetch(f.base+'/api/state',{headers:{authorization:'Bearer '+token}});const d=await r.json();assert.equal(d.capabilities.desktopSources,true);assert.equal(JSON.stringify(d).includes(token),false);assert.equal((await fetch(f.base+'/api/desktop/poll',{method:'POST',headers:{authorization:'Bearer '+token}})).status,404);assert.equal((await fetch(f.base+'/')).status,200);});
test('cross-origin writes and unknown paths cannot reach the cloud',async t=>{const f=await setup(t);const r=await fetch(f.base+'/api/tasks',{method:'POST',headers:{authorization:'Bearer '+token,origin:'https://evil.example','content-type':'application/json'},body:'{}'});assert.equal(r.status,403);assert.equal(f.forwarded.length,0);});

test('storage routes require authentication and explicit confirmation before maintenance',async t=>{let removed=0,locked=0;const server=createDesktopServer({token,publicDir:new URL('../public',import.meta.url),request:async()=>({tasks:[{id:'completed'}],capabilities:{}}),bridge:{status:()=>({busy:false}),maintenance:async work=>{locked++;return work();}},runStorage:{list:()=>({bytes:6,runs:[]}),remove:(runs,tasks)=>{assert.equal(tasks[0].id,'completed');assert.equal(runs[0].id,'run');removed++;return {removed:1};}}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port;const post=body=>({method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(body)});assert.equal((await fetch(base+'/api/run-storage/remove',{method:'POST',body:'{}'})).status,401);assert.equal((await fetch(base+'/api/run-storage/remove',post({runs:[{id:'run'}]}))).status,400);assert.equal(removed,0);assert.equal((await fetch(base+'/api/run-storage/remove',post({confirm:true,runs:[{id:'run'}]}))).status,200);assert.equal(removed,1);assert.equal(locked,1);});

test('desktop forwards conditional cursor and retains local status on small response',async t=>{let seen;const server=createDesktopServer({token,publicDir:new URL('../public',import.meta.url),request:async p=>{seen=p;return {revision:9,unchanged:true,capabilities:{cloud:true}};},bridge:{status:()=>({busy:true})}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const r=await fetch('http://127.0.0.1:'+server.address().port+'/api/state?since=9',{headers:{authorization:'Bearer '+token}});const data=await r.json();assert.equal(seen,'/api/state?since=9');assert.equal(data.unchanged,true);assert.equal(data.tasks,undefined);assert.equal(data.localDesktop.busy,true);});
