import test from 'node:test';
import assert from 'node:assert/strict';
import {handoffTask,isHandoffReplay} from '../public/core/provider-handoff.mjs';
const task=()=>({id:'t',version:2,status:'running',attachments:[],messages:[],artifacts:[],checkpoint:{provider:'codex',executionId:'e1',generation:1}});
const input=()=>({executionId:'e1',generation:1,content:'draft',handoff:{provider:'claude',instructions:'Review draft',reason:'Independent review',acceptance:'Check consistency'}});
test('handoff preserves one task, bounds metadata, fences old owner and supports replay',()=>{const t=handoffTask(task(),input(),{now:()=> '2026-09-21T00:00:00Z',id:()=> 'id'});assert.equal(t.status,'queued');assert.equal(t.checkpoint.provider,'claude');assert.equal(t.version,3);assert.equal(t.checkpoint.executionId,undefined);assert.equal(t.checkpoint.generation,1);assert.equal(t.messages[0].content,'draft');assert.equal(isHandoffReplay(t,input()),true);assert.throws(()=>handoffTask(t,input()),/owner/);});
test('handoff rejects source references, same provider, stale ownership and more than two transitions',()=>{for(const change of [{attachments:[{name:'raw'}]},{checkpoint:{provider:'codex',executionId:'new',generation:2}},{checkpoint:{...task().checkpoint,handoffHistory:[{},{}]}}])assert.throws(()=>handoffTask({...task(),...change},input()));const i=input();i.handoff.provider='codex';assert.throws(()=>handoffTask(task(),i));});
test('oversized handoff must fail without silent truncation',()=>{const i=input();i.handoff.instructions='x'.repeat(12001);assert.throws(()=>handoffTask(task(),i));});
test('only unchanged automatic lease expiry permits delayed handoff recovery',()=>{const t=task();t.status='paused';t.checkpoint.interruptedBy='lease_expiry';t.checkpoint.interruptedVersion=t.version;assert.equal(handoffTask(t,input(),{recoverInterrupted:true}).status,'queued');t.checkpoint.interruptedVersion=1;assert.throws(()=>handoffTask(t,input(),{recoverInterrupted:true}));t.checkpoint.interruptedVersion=t.version;delete t.checkpoint.interruptedBy;assert.throws(()=>handoffTask(t,input(),{recoverInterrupted:true}));});
